### ISSUE TITLE
allow_ping改成false后还是会出现ping的界面？另外感谢大佬，好用

### ISSUE THREAD

**Issue by izeroo** [Redlnn/Ruijie-ePorta-Tool#1]

**Comment by Redlnn** [comment]
有空再康康

**Comment by Redlnn** [comment]
首先感谢能在茫茫的互联网大海中找到本项目，然后有一个`ping 119.29.29.29`是用于判断程序运行时的网络通断的，是核心代码的一部分，等有空的话会将配置文件中的`enable_disconect`的开关应用到这一部分，关闭断网功能后将不再判断是否已联网。喜欢的话可以点一下 star，关注下次更新可以点 watch，谢谢

**Comment by Redlnn** [comment]
已更新~ 可以试试~
