### ISSUE TITLE
大佬有没有考虑出一个教学视频的，对于零基础的小白来说有点难！

### ISSUE THREAD

**Issue by UNOCLOCK** [Redlnn/Ruijie-ePorta-Tool#3]
如题，希望版主能录一个教学视频。

**Comment by Redlnn** [comment]
这两天看看能不能重写一下录个视频？

**Comment by UNOCLOCK** [comment]
> 这两天看看能不能重写一下录个视频？

谢谢大佬！

**Comment by Redlnn** [comment]
> > 这两天看看能不能重写一下录个视频？
> 
> 谢谢大佬！

咕了，过多几天，有点想重写

**Comment by Redlnn** [comment]
> 如题，希望版主能录一个教学视频。

B站视频：<https://www.bilibili.com/video/BV1TZ4y167b6/>

**Comment by UNOCLOCK** [comment]
> > 如题，希望版主能录一个教学视频。
> 
> B站视频：<https://www.bilibili.com/video/BV1TZ4y167b6/>

谢谢版主！
