### ISSUE TITLE
报错问题

### ISSUE THREAD

**Issue by dalaoJAck** [Redlnn/Ruijie-ePorta-Tool#5]
之前使用没有任何问题，可是最近不知道什么原因开始报错了，下附报错相关截图，麻烦大佬看下什么问题，谢谢
[](url)
<img width="298" alt="2022-11-17" src="https://user-images.githubusercontent.com/84699122/202445579-30548b1e-813c-45a5-b268-b3bd91445fa7.png">

**Comment by Redlnn** [comment]
> 之前使用没有任何问题，可是最近不知道什么原因开始报错了，下附报错相关截图，麻烦大佬看下什么问题，谢谢 <img alt="2022-11-17" width="298" src="https://user-images.githubusercontent.com/84699122/202445579-30548b1e-813c-45a5-b268-b3bd91445fa7.png">

我也不太清楚，你的powershell命令可能有问题，无法执行powetshell命令

**Comment by dalaoJAck** [comment]
[请问是这个错了吗，我更新过但还是这样
<img width="277" alt="2022-" src="https://user-images.githubusercontent.com/84699122/202753159-3ec6b67a-667f-46e1-8647-3451408f7ab6.png">

**Comment by Redlnn** [comment]
> [请问是这个错了吗，我更新过但还是这样 <img alt="2022-" width="277" src="https://user-images.githubusercontent.com/84699122/202753159-3ec6b67a-667f-46e1-8647-3451408f7ab6.png">

不太清楚噢你可以试试直接运行源代码
